# Generated by Django 3.1.1 on 2020-10-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usermy_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=40)),
                ('token', models.CharField(default='cR7MOzSR94tkeBwps0gXg0NrJzm0JSFIT5zM6m9s', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='usermy',
            name='token',
        ),
        migrations.AddField(
            model_name='usermy',
            name='tokens',
            field=models.ManyToManyField(blank=True, to='users.Token'),
        ),
    ]
