# Generated by Django 3.1.1 on 2020-10-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201016_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='sent',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='9Mj8p7BwURj7dKD4jEvAWCOpXcESV3w3Om7ptNTF', max_length=50),
        ),
    ]
