# Generated by Django 3.1.1 on 2020-10-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201016_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='sent',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='i93KDaFMRKfXHFBCHkYlzoyxznFSOh4Eer53bmLF', max_length=50),
        ),
    ]
